
name: "bluebell"
mode: "debug"
port: 8084
version: "v0.1.4"
snowflake:
  start_time: "2021-05-14"
  machine_id: 1
log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
#  host: "127.0.0.1"
  host: "mysql8019"
#  port: 3306
  port: 3306
  user: "root"
  password: "root1234"
  dbname: "bluebell"
  max_idle_conns : 50  #maxIdleCount 最大空闲连接数，默认不配置，是2个最大空闲连接
  max_open_conns : 200
redis:
#  host: "127.0.0.1"
  host: "redis507"
#  port: 6379
  port: 6379
  dbname: 0
  password: ""
  pool_size : 100
